version: "3"

services:
  back:
    container_name: jini_back
    build: 
      context: ./jini_backend
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./staticfiles:/usr/src/app/staticfiles
      - ./media:/usr/src/app/media
    # environment:
    #   DJANGO_SETTINGS_MODULE: config.settings.prod  # 배포설정으로 환경변수 변경
    env_file:
      - ./jini_backend/.env
    ports:
      - "8000:8000"

  nginx:
    container_name: nginx
    build: ./nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./staticfiles:/data/static
      - ./media:/data/media
    ports:
      - "80:80"
      # - "443:443"
    depends_on:
      - back

